export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_LOADING = 'SAVE_DATA_LOADING';
export const SAVE_DATA_ERROR = 'SAVE_DATA_ERROR';

export const DELETE_PRODUCTS_LOADING = 'DELETE_PRODUCTS_LOADING';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_ERROR = 'DELETE_PRODUCTS_ERROR';

export const GET_PRODUCT_BYID_LOADING = 'GET_PRODUCT_BYID_LOADING';
export const GET_PRODUCT_BYID_SUCCESS = 'GET_PRODUCT_BYID_SUCCESS';
export const GET_PRODUCT_BYID_ERROR = 'GET_PRODUCT_BYID_ERROR';

export const POST_PRODUCT_LOADING = 'POST_PRODUCT_LOADING';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_ERROR = 'POST_PRODUCT_ERROR';

export const PUT_PRODUCT_LOADING = 'PUT_PRODUCT_LOADING';
export const PUT_PRODUCT_SUCCESS = 'PUT_PRODUCT_SUCCESS';
export const PUT_PRODUCT_ERROR = 'PUT_PRODUCT_ERROR';